### ISSUE TITLE
Access denied for user 'vagrant'@'10.0.2.2'

### ISSUE THREAD

**Issue by starise** [debops/ansible-mariadb#14]
I had problems connecting to mariadb databases in my vagrant machine from the host. I received the error:  ``Access denied for the user 'vagrant'@'10.0.2.2' ``. To solve, i need to specify exactly the required address for every user. Now i have the following on my inventory file:

````yaml
# the following two lines are not sufficient to grant access
mariadb_server_bind_address: '::'
mariadb_server_allow: [ '0.0.0.0' ]

mariadb_databases:
  - name: 'vagrant'

mariadb_users:
  - name: 'vagrant'
    host: '%' # without this does not work
    database: 'vagrant'
    owner: 'vagrant'
````
And now it works. But am i using the right approach? Is this the expected behavior?
Thank you for your amazing work on these roles.
