### ISSUE TITLE
Possibility to create multiple databases for one user

### ISSUE THREAD

**Issue by amette** [debops/ansible-mariadb#34]
I have to create two databases for one system user, which I would love to do something like this:
```yaml
mariadb__users:
  - name: 'someuser'
    owner: 'system-user'
    home: '/var/local/system-user'
    databases: [ 'somedatabase1', 'somedatabase2' ]
```
The 'databases' parameter doesn't exist, that's what I would like to have.
Or is there already another way of achieving this!?

**Comment by drybjed** [comment]
You can instead do something like this:
```yaml
mariadb__databases:
  - name: 'somedatabase1'
  - name: 'somedatabase2'

mariadb__users:
  - name: 'someuser'
    owner: 'system-user'
    home: '/var/local/system-user'
    priv:
      - 'somedatabase1.*:ALL'
      - 'somedatabase2.*:ALL'
```
That should do what you want
