### ISSUE TITLE
Tasks "Grant (default|auxiliary) privileges to users" always report changed

### ISSUE THREAD

**Issue by mathieumd** [debops/ansible-mariadb#36]
It seems that adding `priv: ['*.*:FILE']` to a `mariadb__users` would make both tasks `Grant default privileges to users` and `Grant auxiliary privileges to users` to report a _changed_ status at each runs.

To bypass this, I had to disable `priv_default` and `priv_aux`:

```yaml
mariadb__users:
  - name: 'piwik'
    priv_default: no
    priv_aux: no
    priv:
      - 'piwik.*:ALL'
      - 'piwik\_%.*:ALL'
      - '*.*:FILE'
```

The `SHOW GRANTS for 'piwik'@'localhost';` output does not actually changes between runs, though:

```
+-------------------------------------------------------------------------+
| Grants for piwik@localhost                                              |
+-------------------------------------------------------------------------+
| GRANT FILE ON *.* TO 'piwik'@'localhost' IDENTIFIED BY PASSWORD '*****' |
| GRANT ALL PRIVILEGES ON `piwik`.* TO 'piwik'@'localhost'                |
| GRANT ALL PRIVILEGES ON `piwik\_%`.* TO 'piwik'@'localhost'             |
+-------------------------------------------------------------------------+
```
